- Gemfile
- Gemfile.lock
- config/database.yml
Use the same database in all environments. To get the database running, you must have a version of postgres installed. Once the daemon is set up, you need to run `bundle exec rake db:setup` to create the database and perform the initial migrations.
> Use PostgreSQL in all environments

- app/assets/stylesheets/application.css.scss
- app/views/layouts/_footer.html.erb
Fixes #35.
Change class used on divs in footer to use col-md-3 instead of col-md-4.
Change social-links to inline-block instead of float: left (centers
them).
Fix placement of closing div tag.
> Center columns in footer. Fixes #35.

- app/views/pages/home.html.erb
Fix typo, take out unneeded apostrophe for plural form of Americans
> Fix typo on landing page: American's > Americans

- CONTRIBUTING.md
- fixed clone url example (removed extra `operationcode`)
- clarifies to make a branch off the `master` branch instead of `main project development branch`
> Changes/fixes to contributing.md

- app/assets/stylesheets/application.css.scss
I adjusted the CSS flex-properties so that the apprentice pictures by default line up in one column (`flex-direction: column`) - mobile-first, but when at a screen-size larger than 768px, the media query kicks in to set the `flex-direction:row` to take advantage of larger screen space.  I also added some bottom margin to the `<figure>` elements when at the smaller screen size to visually separate each apprentice profile.
I also imported the bootstrap SASS variables at the top of application.css.scss - used this to reference the bootstrap `$screen-sm-min` variable in the media query.  
@davidmolina @Wimsy113 @Scripore
> Style apprentice pictures to display responsively on smaller screens

- CONTRIBUTING.md
- Procfile
- config/initializers/sidekiq.rb
- config/sidekiq.yml
Fix for #102 
It's likely that Slackbot wasn't working due to too many sidekiq clients and threads trying to use our redis instance at once.  When I took a look at our production logs, I saw lots of this error "2015-12-06T22:30:39.643309+00:00 app[sidekiq.1]: 3 TID-osjt5y8a8 ERROR: Error fetching job: ERR max number of clients reached"
This fix is based on this Stack Overflow solution: http://stackoverflow.com/a/17826254
Here's some more information on the error we were seeing:
https://github.com/mperham/sidekiq/issues/117
http://manuel.manuelles.nl/blog/2012/11/13/sidekiq-on-heroku-with-redistogo-nano/
https://github.com/mperham/sidekiq/wiki/Advanced-Options
> Fix slack bot invite

- config/newrelic.yml
This adds a New Relic config to allow us to monitor our site (we currently have a free account with New Relic for our dyno, but it does not appear to be configured).
After this is deployed, I will add the environmental variable ENV['NEW_RELIC_KEY'] to the Heroku dyno.
> adds new relic config file

- Gemfile
- Gemfile.lock
In attempting to get New Relic working with the site, I realized that we do not have the new relic gem in the app.  This may be why it was not working.  This pull request adds that gem in :)
> adds new relic gem to add monitoring to the Operation Code site

- app/controllers/application_controller.rb
Fixes #124 
Forcing SSL for the test environment was causing the tests to fail.  It should not be needed for the testing environments.
> do not force ssl when running tests

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/veterans_controller.rb
- app/models/veteran.rb
- spec/controllers/veterans_controller_spec.rb
- spec/models/veteran_spec.rb
Fixes #22 
When this is deployed, I will need to add two environmental variables to our Heroku setup.  1 with the API key for our Mailchimp account and the other for the Mailchimp list id.
> Auto add vets to MailChimp

- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/calendar.css.scss
- app/views/pages/calendar.html.erb
Tweaked the calendar a bit for #149 :
* Centered it
* It should scale down at mobile screen sizes instead of overflowing off the screen
* Rounded border-radius and used the native Google Calendar internal CSS options to streamline the calendar appearance and remove unneeded elements (nav buttons, print button, other elements that don't look visually appealing embedded on our website)
I also added 'calendar.css.scss' file to contain the CSS rules specific to the calendar "module" - (see https://smacss.com) and imported the module SASS file in the application.css.scss manifest file.  If anyone else is big on SASS optimization, it might be worth looking into breaking out the entire app's CSS styles into a modular system similar to SMACSS and/or BEM-style naming conventions.
Moving on to …
> Refine calendar page content & styles - emphasis on mobile-friendly

- lib/slack/client.rb
- lib/slack/utils.rb
- spec/lib/slack_client_test.rb
- spec/lib/slack_utils_test.rb
2 commits here. One for adding a fetch method in Slack Client class and one for adding a Slack Utils class for operating on Slack information.
The method added to the Utils class is email_is_registered?
This doesn't completely solve the problem due to the necessities of external automations for an automatic email registration upon receipt but introduces a couple of useful methods.
> Invitation email tests 155 and email registration confirmation

- app/views/pages/codeschools.html.erb
Thinkful is a fully online program with headquarters in NYC.
> Add Thinkful to the list of schools

- app/views/pages/scholarships.html.erb
Adds Node Summit to the scholarship page.
Also separates the list of conferences into two lists - upcoming and past
> adds node summit, separates upcoming and past conferences

- app/views/veterans/registrations/new.html.erb
Removed copy from new.html.erb, because it is being relocated to home.html.erb.
> Update copy on new.html.erb

- app/views/pages/mentorship.html.erb
Making it more concise so the information is more digestible. For example, we already say folks can choose any programming language/stack of their choice so just clutters the page to include an unordered list of some of their options. Also, it makes more sense to simply refer to the program as our Software Mentorship Program instead of the Software Mentor Protege program since we already call it the software mentorship program on the homepage, in the nav menu and in the copy.
> Update copy on mentorship page

- CONTRIBUTING.md
Contributing instructions corrected.
In CONTRIBUTING.md in the Operation Code section the directory was changed from cd operationcode to cd operationcode-upstream
> Fixed cd directory in the Getting Started guide #494 

- app/views/layouts/_header.html.erb
- config/faqs.yml
Updated the faqs.yml link to slack on line 39. Changed Slack link from `operation-code.slack.com` to `http://operation-code.slack.com`. It was missing `http://` to open as external link.
This closes issue #523 .
> Fixed broken Slack link on FAQ > "What are the hours of operation for Operation Code?"

- app/assets/stylesheets/application.css.scss
- app/views/layouts/_header.html.erb
- config/faqs.yml
I added a class to have the bullets appear properly. This closes #522.
**From**
**To**
> Specificity for bullets on FAQ

- app/views/layouts/_header.html.erb
added a target of blank to the blog link for issue #496 
WIth the desire of keeping users in the operationcode application, the fact that the blog currently resides on the medium platform makes the best UX choice to have that link open a new tab/window.  Blank target lets the user's browser make that choice.
> Added target of Blog Link

- CONTRIBUTING.md
When setting up my development environment, I was presented with the attached error. I hadn't started my redis server prior to starting my rails server. This PR will add the instructions to the start the redis server after installing it.
> Tell the contributor to start their redis server

- app/views/pages/home.html.erb
Corrected issue where classes on Why Operation Code subtitle caused a layout bug for the .video-container element below it.
Addresses #562.
> Add video-container to respond Vimeo embed

- app/assets/stylesheets/_colors.scss
- app/assets/stylesheets/application.css.scss
This PR will style the flash message to be a little more intentional. I have also separated the color variables in `application.css.scss` to a new partial, `_colors.scss`. This should allow us to maintain a better brand usage.
Relates to [#296](https://github.com/OperationCode/operationcode/issues/296).
> Style the flash message and separate color variables to separate partial

- app/views/user_mailer/welcome.html.erb
Welcome emailer has a few copy fixes, and includes direct links to our mentorship forms and code of conduct.
> Added links to code of conduct and mentorship

- CONTRIBUTING.md
I added a short paragraph/blurb to CONTRIBUTING.md describing:
* What GitHub is
* Where to find some quality free online training for it
It seems like there are recurring questions from new members (in Slack) on what GitHub is and how to use it.  The current CONTRIBUTING.md briefly explains Git, but not GitHub.  The difference btw/ Git <-> GitHub also seems to be a point of confusion for some.  Hopefully this can clear some of that up.
The training was recommended in the Slack channel by one of of our members who works for GitHub.
If anyone else has ideas on how to improve the wording on this, please edit or comment on this PR.
> Add GitHub free online training to the contributing markdown file

- app/assets/stylesheets/application.css.scss
- app/views/layouts/application.html.erb
This is one possible fix for https://github.com/OperationCode/operationcode/issues/646
Another problem I observed is when there are multiple alerts on a page (by having, say, both `flash[:notice]` and `flash[:error]`). The `.alert` style uses a z-axis, so the multiple alerts would be positioned on top of each other, and all but the first would be hidden.
This PR solves both by putting the alerts into it's own `section` (but I guess it could have been a `container` too). This allows the section to be positioned (with z axis, offset from the top), and multiple alerts can go inside
> Fix notification when signing up (or really any flash)

- CONTRIBUTING.md
@hollomancer In setting up the project to do work I had to run the redis server to avoid fatal errors on the main server. The documentation suggests that you don't have to run the redis server unless you're working on something dealing with `ActiveJob`.  This PR changes the wording a little to say you need it running but will deal with it more directly if you're working on an active job aspect of the project.
> Change the readme to say that you will need to run the redis server

- config/code_schools.yml
The address for The Iron Yard's campus in Austin was incorrect - it listed duplicate info from the Greenville, SC campus (also the company headquarters).  This was also likely causing it to be listed under the South Carolina accordion section on the Code Schools instead of Texas.
Correct address is now listed - can be verified at https://www.theironyard.com/locations/austin
> Code Schools: Correct address for TIY Austin

- .travis.yml
Changed .travis.yml to prevent Travis CI from resetting the working directory and deleting all changes made during the build (the output files from the Jekyll build).
> Prevent Travis CI from deleting Jekyll build artifacts #670

- app/views/layouts/_header.html.erb
While we work through the issues of getting the Jekyll blog properly built w/ TravisCI & Heroku, this link should point to the working Medium blog.
When the Jekyll blog assets are deployed/served, the link can be changed to point to the `/blog` URL again.
related to #624
> Revert header blog link to point to Medium

- app/views/layouts/_header.html.erb
Reverts changes in b9b09d222.  Since the Jekyll blog is building/deploying now, we can link to it from the OC website.
This should close out #624
> Set header blog link to point to Jekyll blog

- CONTRIBUTING.md
This commit doesn't leave linux users out in the cold with no instructions for installing docker.
> Better instructions for getting Docker in CONTRIBUTING.md

- app/views/layouts/_footer.html.erb
Added this using a feature branch instead to avoid unnecessary merge commits.
I altered the Software Mentorship link under "Get Involved" to link to /sign_up. If there's going to be a new mentor sign up page (#629), this can be easily updated once that's completed.
> Allow mentors to sign up without emailing staff@operationcode.org

- config/code_schools.yml
This is a fix to a previous PR.  I updated the second address1 to address2.  There is no issue related to this.
> Fixed duplicate address1 in Coder Camps entry in code_schools.yml

- app/assets/javascripts/application.js
- app/assets/javascripts/modernizr.js
- app/assets/javascripts/timeline.js
- app/assets/partials/_layout.scss
- app/assets/partials/_mixins.scss
- app/assets/partials/_variables.scss
- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/timeline.css.scss
- app/views/layouts/application.html.erb
- app/views/pages/history.html.erb
I converted the history page to a timeline using the link mentioned in the issue at https://codyhouse.co/demo/vertical-timeline/index.html. I made a couple small changes to the CSS from that sournce, notably removing the global styles being applied. I also didn't include the image tags in the HTML for the history page since they were for a movie/picture/location, and that didn't seem to fit well with the timeline here, so I just alternated the colors.
Any items int he history page with Tweets, I added noted with the date on the post, but for the others I was just able to put the year. We may be able to go back and add more if we can get more precise dates on them.
One additional note. There were two items in the history page, one talking about starting to accept donations from Stripe and …
> #278 History page converted to timeline
