README.md, app/views/layouts/_header.html.erb
Here are the steps I took: 
(1) Created an issue
(2) git checkout -b fix_twitter_link
(3) git add -A
(4) git commit -m "Fix Twitter link in README"
(5) git push origin fix_twitter_link
=> Update Twitter link in README

CONTRIBUTORS.md, README.md, app/views/pages/about.html.erb, app/views/pages/codeschools.html.erb
Added contributors and fixed indentation.
=> Contributors

app/assets/javascripts/background.js, app/assets/stylesheets/application.css, app/assets/stylesheets/bootstrap.css, app/assets/stylesheets/bootstrap_and_customization.css.scss, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb, bower_components/bootstrap/less/variables.less
Phone view probably still needs some work.  It would be a good idea to check across multiple devices.  I'd be interested to see how it looks on an iPad.
=> Fix video for full responsiveness.

app/assets/stylesheets/application.css.scss
This should fix the current deployment error.
=> Fix heroku error

app/assets/stylesheets/application.css.scss
Let's test this and see if the images will load.
=> Fix Heroku take 2

app/assets/javascripts/application.js, app/assets/javascripts/jquery.stellar.js, app/assets/stylesheets/application.css.scss, app/assets/stylesheets/bootstrap_and_customization.css.scss, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
Adjusted the navbar for broken div's above old navbar and made it static on page.
Added parallax scrolling.
Fixes #16
=> Fix Frontpage scrolling

app/assets/stylesheets/bootstrap_and_customization.css.scss
=> making drop down menus open on mouse over

app/views/pages/learn.html.erb
Great option that is a little less expensive than Bloc, Thinkful, etc. I took their first course at it was great.
=> Added Tealeaf Academy to Online resources.

Gemfile, Gemfile.lock, Procfile, app/controllers/veterans_controller.rb, app/jobs/slack_inviter_job.rb, app/models/veteran.rb, config/application.rb, config/routes.rb, lib/slack/client.rb
* Adds slack integration to send the user an invite upon sign up.
* Uses ActiveJob for ActiveMailers to get rid of deprecated message
* Remove unused routes file
Closes #21 #44
=> Slack integration

spec/controllers/veterans_controller_spec.rb
=> Remove redis for tests

app/controllers/donations_controller.rb, app/views/donation_mailer/thankyou.html.erb, config/routes.rb
I believe this mailer error was invalidating stripe.
=> Fixed error on mailer that prevented stripe from going through

app/controllers/donations_controller.rb, app/views/donation_mailer/thankyou.html.erb, config/initializers/stripe.rb
fixed donation params so they have first name and last name accessible in the email, added some if else for production keys, added test keys
=> Fixed donation stripe stuff I believe

app/views/donations/_form.html.erb
Fixes issue https://github.com/OperationCode/operationcode/issues/79
@davidmolina
=> set email to be required field.

Gemfile, app/controllers/donations_controller.rb, app/models/donation.rb, app/views/donations/_form.html.erb, config/routes.rb
Added Validation for amount on Donations Model, allowing us to verify if the submission is valid and return the user back to the donations page.
=> Additional Updates for Validation on Donations page

app/assets/stylesheets/application.css.scss
This might fix the issue with the assets.  Not really sure whats going on with that, this is the way you are suppose to include other css files when using SCSS tho.
=> changed import of css files to the SCSS format

app/assets/stylesheets/bootstrap_and_customization.css.scss
Need this in order for it to add the https: automatically.  404 fix
=> fix font import url

app/views/pages/codeschools.html.erb
Add DigitalCrafts to code school page
=> Add DigitalCrafts to code school page

blog/_posts/2015-11-17-linux-academy.markdown
We <3 Linux Academy for supporting Operation Code with free 6 month subscriptions!
=> adds blog post about linux academy

CONTRIBUTING.md
=> Small updates for CONTRIBUTING

app/views/donations/_form.html.erb, app/views/donations/new.html.erb
Moved from the top of page next to "Payment Details".
Fixes #157
=> Cleaned up Comodo Secure Icon

.travis.yml
Fixes #136. This should deploy to our test server for each commit to master. Next step will be to change this to the live site.
=> First pass at CI

.travis.yml
=> Swap travis to prod

Gemfile, Gemfile.lock
=> fix 'thin' referenced twice in Gemfile

app/views/pages/home.html.erb
Remove blank slide from roll on landing page.
Clean up code on home.html.erb.
The blank slide was being caused by the script being in the wrong place. I moved the script to the bottom of the page outside of any `<div>` and found a few tags that did not have closing tags or were unnecessary.
This closes issue #216
=> Remove blank slide from role on landing page.

app/views/pages/codeschools.html.erb
Deep Dive Fullstack offers full funding via the GI Bill.
=> Add Deep Dive Fullstack

public/blog/2016/06/08/node-summit-sf.html
Adds blog post about scholarships to the Node Summit :)
=> adds node summit blog post

js-guide.html
Addresses #199 
/cc @jjhampton 
This is a starting point for the JavaScript Guide. Right now, it's mostly a list of resources, but I'd love to pare it down to the best couple of links under each umbrella. Looking forward to discussing improvements to this doc!
=> Convert outline of JS guide to HTML

app/views/pages/scholarships.html.erb
It does what the subject line says :)
=> adds Code on the Beach and 360iDev conferences to scholarship page

CONTRIBUTORS.md, app/views/layouts/_footer.html.erb, app/views/pages/sponsors.html.erb, blog/_posts/2016-06-27-meet-codeconf-la-conrad-hollomon.markdown, public/blog/2016/06/27/meet-codeconf-la-conrad-holloman.html, public/blog/feed.xml, public/blog/index.html, public/blog/tag/News/index.html
=> add O'Reilly Media Partner Image 

app/views/pages/scholarships.html.erb
=> fixes #263

app/controllers/pages_controller.rb, app/views/layouts/_header.html.erb, app/views/pages/fellowships.html.erb, config/routes.rb
=> Add fellowships copy

app/views/devise/passwords/edit.html.erb
=> Fix password reset styling

app/views/layouts/_footer.html.erb
Placed the Guidestar into what I considered to be a logical location within the footer.
=> Add Guidestar icon to _footer.html.erb

app/views/layouts/_footer.html.erb
Updated GuideStar logo to latest link to the footer.
=> Update GuideStar Logo footer.html.erb

config/code_schools.yml
We're a non-profit code school out of New Orleans that is starting to build outreach efforts and find scholarships for veterans.
=> Add Operation Spark to code school list

.travis.yml, app/controllers/application_controller.rb, app/controllers/profile/mentees_controller.rb, app/controllers/profile_controller.rb, app/mailers/mentee_mailer.rb, app/models/mentor.rb, app/models/veteran.rb, app/views/mentee_mailer/welcome.html.erb, app/views/profile/home/_details.html.erb, app/views/profile/mentees.html.erb, app/views/profile/mentees/_your_mentee.html.erb, app/views/profile/mentees/show.html.erb, config/routes.rb, db/migrate/20160720042822_add_bio_to_veterans.rb, db/migrate/20160802182934_add_welcomed_to_veterans.rb, db/schema.rb, test/fixtures/veterans.yml, test/mailers/mentee_mailer_test.rb, test/models/veteran_test.rb
=> Add Welcome Mailer for Mentors

app/controllers/profile_controller.rb, app/views/profile/edit_bio.html.erb, app/views/profile/home.html.erb, app/views/profile/home/_bio.html.erb, app/views/profile/mentees/_unclaimed_mentee.html.erb, config/routes.rb, config/sidekiq.yml, test/fixtures/veterans.yml
=> Fixes for welcome email

app/mailers/mentee_mailer.rb, app/models/veteran.rb, test/mailers/mentee_mailer_test.rb, test/models/veteran_test.rb
Fixes #363 and kind of helps with #364
=> BCC mentorship on welcome email

app/views/pages/jsguide.html.erb
Deleted the header portion of the js page and placed contents within a container. Looks centered online == better look.
=> Fix js page

app/views/pages/board.html.erb
=> Remove dup board member & clean up layout

app/views/pages/home.html.erb
Move the code, updated content, and sign-up form from revised #new.html.erb  - PR #336 to the home page under the join now button.
=> Add old form copy to home.html.erb

app/views/pages/press.html.erb
=> Add lastest interviews

app/views/code_schools/index.html.erb
=> Fix typo #369

CONTRIBUTORS.md, app/views/layouts/_header.html.erb
Fixes 431 and spelling error in contributors.
=> Fixes #431 and spelling error in contributors.

app/views/pages/home.html.erb
I removed and updated some of the copy on the homepage. It's too much as is and still is with this change. But it's a step in the right direction. More edits and cuts to come...
=> Updated home.html.erb 

app/views/pages/home.html.erb
=> Copy edits home.html.erb

app/views/pages/home.html.erb
Is there another upcoming event?
=> Removing GitHub Universe

Gemfile.lock, app/views/pages/sponsors.html.erb
Gemfile.lock seems to be updated based on my environment.
=> issue 451 add digital ocean to sponsors

app/views/layouts/_header.html.erb
The drop down menu in "What We Do" is now reordered by popularity.
What We Do
- Code Schools
- Scholarship Program
- Software Mentorship
- Employer Services
- Web Application Development
=> Reorder "What We Do" Menu section issue #489

CONTRIBUTING.md
These are two references on git that I wish I had when I started working on a repository with other people and need to do more than `git push origin master` . Hope they help.
=> Add a couple references on git

app/views/veterans/registrations/new.html.erb
Tried to make it a little bit sharper.
=> Copy on sign up page update

app/views/pages/home.html.erb
I'm giving our copy a logical flow. First we're telling them in bold letters that this is the fastest way for them to get coding. Our most popular pages and requests for info are about code schools, scholarships, and jobs. So it makes sense for our copy to say we'll provide them that and more. The copy changes will also help with SEO.
=> Update homepage copy

app/views/code_schools/index.html.erb
More concise. Also centered the section headers.
=> Updated copy on code schools page

app/views/pages/home.html.erb
Combined some copy to make it crisper around the teach me to code button.
=> Homepage copy update

app/views/layouts/_header.html.erb, config/routes.rb
**Resolves**
https://github.com/OperationCode/operationcode/issues/486
=> Adding a swag link in the nav

app/views/layouts/_header.html.erb
=> Reduced size of join button

config/faqs.yml
=> Fix typo in FAQ

app/assets/stylesheets/deploy.css.scss
Reduce Size of the Operation Code Icon
=> fix issue #312

CONTRIBUTING.md
=> Add Node Install Instructions

config/code_schools.yml
=> Added Codeup

config/code_schools.yml
Deep Dive Fullstack now accepts GI Bill funding. Updated our record in code_schools.yml to reflect this  change.
=> update deep dive fullstack va_accepted true

app/views/layouts/_footer.html.erb
=> Updated guidestar.org image to use HTTPS

app/views/layouts/application.html.erb
#540 
Substituted a few words and rearranged to convey the same message in a more compact format
=> Amended meta tag according to #540

app/assets/stylesheets/application.css.scss
For better text readability - issue #551
=> Updated opacity for home page slider images

CONTRIBUTORS.md
This PR will add me to the contributor list.
=> add mwagz as contributor

Gemfile.lock, config/code_schools.yml
Added App Academy to `code_schools.yml`
=> Added App Academy to the list of code schools

CONTRIBUTING.md
- Fixed numerous grammar errors, especially missing commas and mis-capitalized words.  
- Improved phrasing.
- Implemented proper indentation. 
- Bolded the text "Operation Code" throughout the documentation. 
- Added a line about rbenv also working well. 
- Inserted a link to Google Javascript Style Guide
- Added a line for `thin start --ssl` in the local dev env. 
- Added a line about recommending Cloud9 for total nubs. 
- Moved the section about forking the repository from the "Working On Your Issues" section to "Setting Up Your Environment/Operation Code". 
- Removed "Contributing Blog Posts" section as the MD file does not exist. 
- Re-ordered the sections: "Setup your environment" section should come before all of the "Issues" sections.
=> Contributing.md Improvements

config/code_schools.yml
Hi team - 
This pull request is for changes to the config/code_schools.yml. We added two Tech Elevator locations (Cleveland, Ohio and Columbus, Ohio).
=> Tech Elevator Code School Addition

config/code_schools.yml
Conrad - I updated the Galvanize profiles for Golden Triangle, Boulder and San Francisco. The url's and physical addresses were outdated. I added the Golden Triangle campus which accepts the GI Bill as we discussed. Let me know if this all looks good.
=> Updated code school.yml

Gemfile.lock, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb
Update donate button to a single option.
=> Add donorbox button (#571)

CONTRIBUTORS.md
I'm adding my name to the contributor list.
=> add ver2point0 to contributor list

app/views/pages/staff.html.erb
I added my twitter handle to the staff bio with link. No other changes made.
=> JM-ADD twitter handle to Jay Miller on staff page

app/views/devise/mailer/reset_password_instructions.html.erb, config/locales/devise.en.yml
I made the grammar changes in the body of the email and I changed the welcome message in the email subject line.  I wanted to change the file name of the email to better reflect what it actually is but I don't know how to locate every instance of the file name.
=> Issue #598 completed

CONTRIBUTING.md, CONTRIBUTORS.md
Added some official Postgresql installers and n-install for node.
=> Added installation instructions on CONTRIBUTING.md

doc/Live-Coding.md
This addresses #632.
/cc @hollomancer for review.
=> Add a document linking to all of the live coding sessions

README.md
Simply removed unnecessary periods from the ends of three URLs in the Readme file.
=> Readme update - removed unnecessary periods

app/assets/stylesheets/application.css.scss, app/assets/stylesheets/deploy.css.scss, app/assets/stylesheets/success_stories.css.scss, app/views/code_schools/index.html.erb, app/views/layouts/_header.html.erb, app/views/pages/board.html.erb, app/views/pages/deploy.html.erb, app/views/pages/faq.html.erb, app/views/pages/mentorship.html.erb, app/views/pages/staff.html.erb, app/views/pages/success_stories.html.erb
Did not really go through the issue list, but I saw a lot of issues with the UI that needed addressing.  Also fixed mobile menu and logo placement issues I saw.
=> fix a bunch of issues I saw with the ui.

.travis.yml
Attempting to resolve issues w/ Heroku buildpack failure: https://devcenter.heroku.com/articles/buildpacks#detection-failure
=> Return to the Rails app base directory after Jekyll build complete #673

app/views/pages/staff.html.erb
=> 672 Updating Edward Gutierrez's staff profile

Gemfile, config/application.rb
=> Adds logstash formatter

Gemfile, app/assets/javascripts/application.js, app/assets/javascripts/veterans.js.coffee, app/assets/stylesheets/application.css.scss
Added the leaflet marker clustering plugin.
=> Issue #699 Implemented marker clustering

config/environments/production.rb
It doesn't appear to like secrets loaded from rancher.
=> Revert back to env for sendgrid

Rakefile
=> Makes the operation code lib available to rake tasks

config/code_schools.yml
Added Coder Camps information to code_schools.yml
=> Added Coder Camps to code_school.yml

app/views/pages/staff.html.erb, config/code_schools.yml
=> Added Nick Krzemienski to staff page

CONTRIBUTING.md, PULL_REQUEST_TEMPLATE.md
Wrote this up with the changes/additions specified in the issue discussion.
Let me know if you guys want something different or more substantial.
=> Issue #686- Add PR guidelines to docs

app/views/pages/board.html.erb
Adding Dr. Tyrone Grandison to /board for issue #738
=> Add Tyrone to /board #738

README.md
=> update contributors link
